import type { Product } from '../types';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-mangalsutra-01',
    name: 'Classic 24K Gold-Plated Floral Mangalsutra',
    slug: 'classic-gold-plated-mangalsutra',
    sku: '90S-MS-001',
    shortDescription: 'Exquisite handcrafted black-bead double chain mangalsutra with 24K micro-gold plated floral pendant and sparkling Austrian cubic zirconia stones.',
    description: `Celebrate timeless Indian tradition with the 90s chya athavani Jewellery Classic Floral Mangalsutra. 
    Crafted from premium hypoallergenic brass and coated with a high-durability 24K micron gold finish, this mangalsutra features auspicious dual-strand black beads woven with precision. 
    The centerpiece showcases a delicate floral medallion encrusted with brilliant hand-set Austrian CZ diamonds that radiate exceptional fire and luster. 
    Designed for daily wear elegance as well as festive celebrations.`,
    price: 899,
    mrp: 2499,
    discountPercentage: 64,
    primaryImage: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1000&q=85',
    images: [
      'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
    ],
    category: 'Mangalsutra',
    material: 'Premium Brass Base Alloy',
    finish: '24K Micro Gold Plating (High Lustre)',
    color: 'Yellow Gold & Jet Black',
    size: '18 Inches Chain Length + 2 Inch Extender',
    weight: '24 grams',
    occasion: 'Daily Wear, Festive, Anniversary, Karwa Chauth',
    packageContents: '1 x Designer Mangalsutra, 1 x Premium Velvet Jewellery Box, 1 x Authenticity Card',
    careInstructions: 'Keep away from direct perfume, water, and deodorants. Wipe gently with a soft cloth after use and store in an airtight pouch.',
    stock: 28,
    shippingCharge: 0,
    status: 'active',
    seoTitle: 'Classic 24K Gold Plated Floral Mangalsutra | 90s chya athavani Jewellery',
    seoDescription: 'Buy luxury gold-plated floral mangalsutra online at ₹899. Free delivery across India on WhatsApp orders.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-kundan-choker-02',
    name: 'Royal Heritage Kundan & Pearl Choker Set',
    slug: 'royal-heritage-kundan-pearl-choker',
    sku: '90S-NC-002',
    shortDescription: 'Regal Rajputana style handcrafted Jadau Kundan choker necklace with cascading mint-green emerald drops and matching statement earrings.',
    description: `Elevate your festive attire with our breathtaking Royal Heritage Kundan & Pearl Choker by 90s chya athavani Jewellery. 
    Drawing inspiration from royal Rajasthani heirloom jewellery, this masterpiece is adorned with hand-cut polki kundan stones, clustered Basra pearls, and jade green quartz droplets. 
    Comes with adjustable zari dori (thread) for a customized neckline fit and includes matching heavy Chandbali earrings with Maang Tikka.`,
    price: 1899,
    mrp: 4999,
    discountPercentage: 62,
    primaryImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1611591475152-4c09a33a4042?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1000&q=85',
    ],
    category: 'Necklace Sets',
    material: 'Copper-Brass Alloy with Jadau Kundan',
    finish: 'Antique Matte Gold Polish with Meenakari back work',
    color: 'Gold, Pearl White & Jade Green',
    size: 'Choker Collar with Adjustable Dori',
    weight: '95 grams (Necklace + Earrings)',
    occasion: 'Wedding, Reception, Sangeet, Festive Gala',
    packageContents: '1 x Kundan Choker, 1 Pair Matching Jhumka Earrings, 1 x Maang Tikka, Luxury Gift Case',
    careInstructions: 'Avoid contact with moisture, sprays, and chemicals. Store flat in the provided velvet case.',
    stock: 14,
    shippingCharge: 0,
    status: 'active',
    seoTitle: 'Royal Heritage Kundan & Pearl Choker Set | 90s chya athavani Jewellery',
    seoDescription: 'Handcrafted bridal kundan choker set with matching earrings at ₹1,899. WhatsApp delivery guarantee.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-temple-jhumka-03',
    name: 'South Indian Temple Lakshmi Jhumka Earrings',
    slug: 'temple-lakshmi-jhumka-earrings',
    sku: '90S-ER-003',
    shortDescription: 'Traditional Kemp stone temple jewellery jhumkas featuring Goddess Lakshmi motif, ruby-pink stones, and dancing pearl beads.',
    description: `Immerse in spiritual majesty with our authentic South Indian Temple Lakshmi Jhumkas from 90s chya athavani Jewellery. 
    Hand-carved with intricate motifs of Goddess Lakshmi seated on a lotus pedestal, complemented by rich ruby-red Kemp glass stones and antique brushed matte finish. 
    The bell jhumka has delicate cluster pearl drops that create a rhythmic sway with every step. Perfect pairing for Kanjeevaram and silk sarees.`,
    price: 699,
    mrp: 1799,
    discountPercentage: 61,
    primaryImage: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85',
    images: [
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
    ],
    category: 'Earrings',
    material: 'Pewter & Brass Metal with Kemp Glass Stones',
    finish: '22K Temple Antique Matte Gold',
    color: 'Antique Gold & Ruby Pink',
    size: 'Length: 6.5 cm, Width: 3.2 cm',
    weight: '38 grams (Pair)',
    occasion: 'Temple Visits, Poojas, Traditional Weddings, Diwali',
    packageContents: '1 Pair Temple Jhumkas, Spare Push-back stoppers, Velvet Box',
    careInstructions: 'Clean with a soft dry cotton swab. Do not use chemical liquid jewellery dips.',
    stock: 35,
    shippingCharge: 50,
    status: 'active',
    seoTitle: 'South Indian Temple Lakshmi Jhumka Earrings | 90s chya athavani Jewellery',
    seoDescription: 'Antique gold matte temple jhumkas with Kemp stones at ₹699. Order directly on WhatsApp.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-rose-gold-bracelet-04',
    name: 'Sparkling Clover Rose Gold Tennis Kada Bracelet',
    slug: 'sparkling-clover-rose-gold-bracelet',
    sku: '90S-BR-004',
    shortDescription: 'Contemporary openable cuff bracelet in 18K rose gold finish, studded with high-grade AAA Austrian zircon crystals and clover charm.',
    description: `A modern statement of understated luxury. The 90s chya athavani Jewellery Sparkling Clover Kada is crafted in surgical-grade stainless alloy and wrapped in an ultra-smooth 18K rose gold PVD coating that will not tarnish or fade. 
    Features an invisible spring-lock clasp for effortless one-handed wearing and a four-leaf clover motif symbolizing good fortune and enduring love.`,
    price: 749,
    mrp: 1999,
    discountPercentage: 62,
    primaryImage: 'https://images.unsplash.com/photo-1611591475152-4c09a33a4042?auto=format&fit=crop&w=1000&q=85',
    images: [
      'https://images.unsplash.com/photo-1611591475152-4c09a33a4042?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1000&q=85',
    ],
    category: 'Bracelets & Kadas',
    material: 'Anti-tarnish Titanium Stainless Steel Alloy',
    finish: '18K Rose Gold High Gloss Polish',
    color: 'Rose Gold & Crystal Clear',
    size: 'Inner Diameter: 5.8 cm (Fits wrist sizes 2.4 to 2.6)',
    weight: '16 grams',
    occasion: 'Office Wear, Cocktails, Date Night, Casual Chic',
    packageContents: '1 x Rose Gold Kada Bracelet, 1 x Microfiber Cleaning Cloth, 1 x Gift Box',
    careInstructions: 'Water-resistant, but avoid prolonged soaking in hot springs or chlorinated pools to retain shine.',
    stock: 20,
    shippingCharge: 50,
    status: 'active',
    seoTitle: 'Sparkling Clover Rose Gold Tennis Kada Bracelet | 90s chya athavani Jewellery',
    seoDescription: 'Buy anti-tarnish 18K rose gold clover bracelet at ₹749. Direct WhatsApp checkout.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-polki-necklace-05',
    name: 'Imperial Polki Bridal Rani Haar & Earring Set',
    slug: 'imperial-polki-bridal-rani-haar',
    sku: '90S-RH-005',
    shortDescription: 'Grand multi-layered bridal Rani Haar necklace with uncut Polki stones, handcrafted Meenakari peacock pendant and hanging emerald beads.',
    description: `Command royalty on your special day with the 90s chya athavani Jewellery Imperial Polki Rani Haar. 
    Measuring an impressive 26 inches with 5 tiered strands of radiant cultured pearls and uncut Polki diamond settings, this necklace crowns any bridal lehenga or Banarasi saree. 
    The grand peacock pendant is hand-painted in traditional Jaipur Meenakari art on the reverse side.`,
    price: 2499,
    mrp: 6999,
    discountPercentage: 64,
    primaryImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85',
    ],
    category: 'Bridal Jewellery',
    material: 'High-Purity Copper with Jadau Setting',
    finish: '24K Vintage Antique Gold with Jaipur Meenakari',
    color: 'Antique Gold, Emerald Green & Pearl',
    size: 'Long Necklace 26 Inches + Adjustable Thread',
    weight: '140 grams (Full Set)',
    occasion: 'Bridal, Wedding Ceremony, Sangeet Night',
    packageContents: '1 x Grand Rani Haar, 1 Pair Heavy Jhumkas, 1 x Luxury Hardbound Wooden Jewellery Box',
    careInstructions: 'Store in dry airtight container. Never spray perfume directly onto polki stones.',
    stock: 8,
    shippingCharge: 0,
    status: 'active',
    seoTitle: 'Imperial Polki Bridal Rani Haar Set | 90s chya athavani Jewellery',
    seoDescription: 'Grand 5-layer polki bridal rani haar necklace at ₹2,499 with free insured shipping across India.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
